### ISSUE TITLE
robots: cron job to remove old data from cdx_backup

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#44]
was crawl diss  cdx-merge-sort-publish step, when it runs cleanly, copies CDX files from `/web-archiving-stacks/data/indices/cdx_working` to `/web-archiving-stacks/data/indices/cdx_backup` . 

There is no cleanup of `cdx_backup` -- we should have a cron clean out files older than XXX.

There is low risk as 
- the files have been processed cleanly
- we can regenerate cdx files from warcs

**Comment by ndushay** [comment]
@nullhandle  should decide the policy of when files "age out" of `cdx_backup`.   Then we should file a SAR ticket for creating the cron job to do this???

**Comment by nullhandle** [comment]
@ndushay Perhaps the job shouldn't clean out backup files based on time elapsing but rather based on the most recently cleanly-completed job? At any time, we should ideally have a drop-in backup for the production index. So every time the cdx-merge-sort-publish step terminates successfully, the penultimate backup index should be deleted. Does that make sense?

**Comment by ndushay** [comment]
Yes - makes sense.  It seems more of a robot step this way, than a cron job.  What do you think @drh-stanford, @lmcglohon  ?

**Comment by drh-stanford** [comment]
The `cdx_backup` is the *individual* CDX files (i.e., per WARC) and does not have a penultimate backup copy of the master CDX file. There's ~200K CDX files right now in `cdx_backup` taking up 100GB. I would argue that we can delete all of them (since we can compute them again if needed from the WARCs), and that we can change the cdx-merge robot to just delete the working copy and not even back them up.

If you want a disaster recovery copy of the master index (i.e., a single `index.cdx`), that's easy enough to do, but that's not what's happening now.

Another problem is that error handling isn't smart enough to clean up files in `cdx_working`.  But the data in there is <1GB so we probably don't need to worry about it. See #21 for background.

**Comment by nullhandle** [comment]
Cleaning up all of them sounds fine to me.

**Comment by ndushay** [comment]
See #73 as well - these are duplicates.

**Comment by lwrubel** [comment]
`cdx_backup` now contains 279GB and 20,877 directories.

`cdx_working` contains 17GB.

**Comment by mjgiarlo** [comment]
We recommend holding off on considering these until after we're successfully switched over to pywb.

**Comment by lwrubel** [comment]
Closing in favor of #535.
