### ISSUE TITLE
Only top manual bar appear in thumbnail

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was_robot_suite#570]
Only top manual bar appear in thumbnail generated for the following druids.

https://argo.stanford.edu/view/druid:qz318tr1163
https://argo.stanford.edu/view/druid:pt765ph1166
https://argo.stanford.edu/view/druid:yt314nh6146
https://argo.stanford.edu/view/druid:pz824rs5553
https://argo.stanford.edu/view/druid:pn898yr9026
https://argo.stanford.edu/view/druid:nw156gq9747
https://argo.stanford.edu/view/druid:vz140sx2206
https://argo.stanford.edu/view/druid:kb975bq9211
https://argo.stanford.edu/view/druid:fg723nr1061
https://argo.stanford.edu/view/druid:mg716wx8565
https://argo.stanford.edu/view/druid:st572rc5915

**Comment by mjgiarlo** [comment]
@peterchanws @vivnwong This could use prioritization.

**Comment by andrewjbtw** [comment]
I took another look at this because I thought there was a chance that something might have changed in SWAP in the past few months that could have affected thumbnail generation. But I'm still seeing the same issue with the first druid on Peter's list after I re-ran thumbnail generation: https://argo.stanford.edu/view/druid:qz318tr1163

On closer inspection, I think at least for [that seed](https://swap.stanford.edu/was/20151217051727mp_/http://weibo.com/u/2928914240/) the problem isn't so much with the thumbnail as it is with a redirect. SWAP initially loads a page that has only the top bar and that's what's captured in the thumbnail. But then the page redirects to [a login page](https://swap.stanford.edu/was/20151217051755/http://weibo.com/login.php), which is not captured in the thumbnail.

**Comment by peterchanws** [comment]
More examples on the same issue from another collection:
https://searchworks.stanford.edu/view/tq044hx0493
https://searchworks.stanford.edu/view/wp411mb1284
https://searchworks.stanford.edu/view/ch137hm5080
https://searchworks.stanford.edu/view/sr518bj9915
https://searchworks.stanford.edu/view/bv275cp7117
https://searchworks.stanford.edu/view/nt924xf0453

**Comment by edsu** [comment]
I spot checked a few of the seed URLs in the first set, which all appear to be weibo sites whose earliest crawl was a redirect to a login page? I guess we have a question here of whether following the redirect is the desired behavior for the screenshot, or if the Thumbnail generator should look for the first snapshot that has a 200 OK HTTP response?

Some of the other ones in the second set appear to be timing issues where the page is taking too long to render?  For example https://searchworks.stanford.edu/view/wp411mb1284

**Comment by peterchanws** [comment]
My take is that we should create thumbnails after login.

Peter



Peter Chan

Web Archivist

Stanford University Libraries

Green Library, 557 Escondido Mall

Stanford, CA  94305-6064

(650) 924-2404 | ***@***.***

https://swap.stanford.edu/was/20230717122654/https://library.stanford.edu/people/pchan3

Pronouns: he/him/his


***@***.***?anonymous&ep=owaSlotsEmailSignature>                Book time to meet with ***@***.***?anonymous&ep=owaSlotsEmailSignature>
________________________________

**Comment by edsu** [comment]
I'm reopening this till we can confirm the changes actually fix the problem :-)

**Comment by peterchanws** [comment]
[like]  Peter Chan reacted to your message:
________________________________

**Comment by andrewjbtw** [comment]
Yes, the longstanding image caching issue applies here and the images should turn over to new ones after some amount of time that doesn't seem possible to predict.
